apiVersion: v1
kind: Secret
metadata:
  name: ticket-secrets
  namespace: ticket-platform
type: Opaque
stringData:
  DB_HOST: "ticket-db"
  DB_PORT: "5432"
  DB_USER: "ticketuser"
  DB_PASSWORD: "CHANGE_ME_IN_PROD"
  DB_NAME: "ticketdb"
  REDIS_HOST: "ticket-redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "CHANGE_ME_IN_PROD"
  JWT_SECRET: "CHANGE_ME_IN_PROD"
  JWT_EXPIRES_IN: "24h"
